# Generated by Django 4.1.7 on 2023-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_login_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=20)),
                ('officer_id', models.IntegerField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
            ],
        ),
    ]
