# Generated by Django 4.1.7 on 2023-04-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_officer_officer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fault_driver', models.CharField(max_length=100)),
                ('fault_vehicle_number', models.CharField(max_length=100)),
                ('fault_driver_name', models.CharField(max_length=100)),
                ('fault_driver_email', models.EmailField(max_length=254)),
                ('fault_driver_phone', models.CharField(max_length=100)),
                ('fault_driver_address', models.TextField()),
                ('victim_vehicle_number', models.CharField(max_length=100)),
                ('victim_name', models.CharField(max_length=100)),
                ('victim_email', models.EmailField(max_length=254)),
                ('victim_phone', models.CharField(max_length=100)),
                ('victim_address', models.TextField()),
                ('injuries', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
