# Generated by Django 4.1.7 on 2023-05-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_officer_officer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_login',
            name='username',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
